# Generated by Django 4.2 on 2023-04-26 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appinfo",
            name="createdOn",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
