# Generated by Django 4.2 on 2023-05-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0002_alter_appinfo_createdon"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("studentID", models.IntegerField(unique=True)),
                ("name", models.TextField()),
                ("section", models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name="appinfo",
            name="text",
            field=models.TextField(default="Enter description here"),
        ),
        migrations.AlterField(
            model_name="appinfo",
            name="userId",
            field=models.IntegerField(unique=True),
        ),
    ]
